In [1]:
import pandas as pd
import numpy as np

/home/mao919/anaconda3/envs/py37-start/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]:
df = pd.read_csv("Final_Dataframe.csv")
df.head()

,brand,laptop_name,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max
0,HP,Notebook 14-df0008nx,14.0,Intel Celeron N4000,Intel HD Graphics 600,64 GB (eMMC),1259.0,1259.0,0 / 5
1,Lenovo,IdeaPad 330S-14IKB,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1 TB HDD,1849.0,2099.0,3.3 / 5
2,Huawei,MateBook D Volta,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256 GB SSD,2999.0,3799.0,0 / 5
3,Dell,Inspiron 15 3567,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1 TB HDD,1849.0,1849.0,0 / 5
4,Asus,VivoBook 15 X510UR,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1 TB HDD,2499.0,3149.0,0 / 5

In [3]:
df.dtypes

brand              object
laptop_name        object
display_size      float64
processor_type     object
graphics_card      object
disk_space         object
discount_price    float64
old_price         float64
ratings_5max       object
dtype: object

In [4]:
print(df.shape)
df.nunique()

(205, 9)

brand               9
laptop_name       134
display_size       11
processor_type     26
graphics_card      52
disk_space         30
discount_price    124
old_price         104
ratings_5max       16
dtype: int64

In [5]:
df.isnull().sum()

brand             0
laptop_name       1
display_size      0
processor_type    0
graphics_card     0
disk_space        0
discount_price    0
old_price         0
ratings_5max      0
dtype: int64

In [6]:
df.fillna(method='bfill', inplace=True)

## Start from the 'rating column'
#### lets remove the denominator and just leave an integer

In [7]:
df2 = df.copy(deep=True)
df2['ratings_5max'] = df['ratings_5max'].apply(lambda x: float(x.split()[0]))
df2.head()

,brand,laptop_name,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max
0,HP,Notebook 14-df0008nx,14.0,Intel Celeron N4000,Intel HD Graphics 600,64 GB (eMMC),1259.0,1259.0,0.0
1,Lenovo,IdeaPad 330S-14IKB,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1 TB HDD,1849.0,2099.0,3.3
2,Huawei,MateBook D Volta,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256 GB SSD,2999.0,3799.0,0.0
3,Dell,Inspiron 15 3567,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1 TB HDD,1849.0,1849.0,0.0
4,Asus,VivoBook 15 X510UR,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1 TB HDD,2499.0,3149.0,0.0

## Disk Space

###### lets check out the values

In [8]:
df2.disk_space.apply(lambda x: x.split()[-1]).unique()

array(['(eMMC)', 'HDD', 'SSD', 'SSD)', 'Flash)'], dtype=object)

###### now correct the typo with 'SSD)' and 'Flash)' and separate disk type in a different column

In [9]:
typeDict = {'(eMMC)': 'eMMC', 'HDD': 'HDD', 'SSD': 'SSD', 'SSD)': 'SSD', 'Flash)': 'Flash'}
df2['disk_type'] = df2['disk_space'].map(lambda x: typeDict[x.split()[-1]])
df2['disk_space'] = df2['disk_space'].apply(lambda x: float(x.split()[0])*1024 if x.split()[1] == 'TB' else float(x.split()[0]))
df2.head()

,brand,laptop_name,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max,disk_type
0,HP,Notebook 14-df0008nx,14.0,Intel Celeron N4000,Intel HD Graphics 600,64.0,1259.0,1259.0,0.0,eMMC
1,Lenovo,IdeaPad 330S-14IKB,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1024.0,1849.0,2099.0,3.3,HDD
2,Huawei,MateBook D Volta,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256.0,2999.0,3799.0,0.0,SSD
3,Dell,Inspiron 15 3567,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1024.0,1849.0,1849.0,0.0,HDD
4,Asus,VivoBook 15 X510UR,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1024.0,2499.0,3149.0,0.0,HDD

##### ok now that thats done. We can treat this new column as a categorical column to create dummy values for. will do it at the end

## Graphics card

In [10]:
df2.graphics_card.unique()

array([' Intel HD Graphics 600', ' Intel UHD Graphics 620',
       ' NVIDIA GeForce MX150 (2 GB)', ' Intel HD Graphics 620',
       ' NVIDIA GeForce 930MX (2 GB)', ' AMD Radeon 530 (4 GB)',
       ' Intel UHD Graphics 617', ' AMD Radeon 530 (2 GB)',
       ' AMD Radeon R5', ' Intel GMA HD', ' Intel HD Graphics 6000',
       ' Radeon Pro 555X GDDR5 (4 GB)', ' Intel Iris Plus Graphics 655',
       ' NVIDIA GeForce MX150 (4 GB)', ' NVIDIA GeForce MX250 (4 GB)',
       ' NVIDIA GeForce MX110 (2 GB)', ' NVIDIA GeForce MX230 (2 GB)',
       ' Intel HD Graphics 615', ' NVIDIA GeForce MX130 (4 GB)',
       ' NVIDIA GeForce GTX 1050 Ti (4 GB)',
       ' NVIDIA GeForce MX130 (2 GB)', ' AMD Radeon 520 (2 GB)',
       ' AMD Radeon 530M (4 GB)', ' Intel Graphics 620',
       ' Intel UHD Graphics 600', ' AMD Radeon 540 (4 GB)',
       ' NVIDIA GeForce MX250 (2 GB)', ' NVIDIA GeForce GTX 1050 (3 GB)',
       ' Intel Iris Plus Graphics 645', ' Intel HD Graphics 400',
       ' Intel Iris Plus Graphics 640', ' Intel HD Graphics 505',
       ' Intel HD Graphics 500', ' Radeon Pro 560X GDDR5 (4 GB)',
       ' NVIDIA GeForce GTX 1080 (8 GB) SLI',
       ' NVIDIA GeForce GTX 1070 (8 GB)',
       ' NVIDIA GeForce GTX 980M (8 GB)', ' AMD Radeon R9-M370X (2 GB)',
       ' NVIDIA GeForce GTX 1080 (8 GB)',
       ' NVIDIA GeForce GTX 1050 (4 GB)', ' Radeon Pro 555 GDDR5 (2 GB)',
       ' AMD Radeon 535 (2 GB)', ' Intel Iris Pro Graphics',
       ' Intel Iris Plus Graphics 650', ' Intel HD Graphics 520',
       ' NVIDIA GeForce GT 940MX (2 GB)', ' AMD Radeon R5-M340 (2 GB)',
       ' AMD Radeon R7-M445 (4 GB)', ' NVIDIA GeForce 940MX (4 GB)',
       ' NVIDIA GeForce 940MX (2 GB)', ' Intel Iris Graphics 550',
       ' AMD Radeon R5-M430 (2 GB)'], dtype=object)

##### replace graphic card names with benchmark

In [11]:
d = {
    ' Intel HD Graphics 600': 153,
    ' Intel UHD Graphics 620': 1050,
    ' NVIDIA GeForce MX150 (2 GB)': 2359,
    ' Intel HD Graphics 620': 921,
    ' NVIDIA GeForce 930MX (2 GB)': 1336,
    ' AMD Radeon 530 (4 GB)': 932,
    ' Intel UHD Graphics 617': 869,
    ' AMD Radeon 530 (2 GB)': 932,
    ' AMD Radeon R5': 389,
    ' Intel GMA HD': 96,
    ' Intel HD Graphics 6000': 843,
    ' Radeon Pro 555X GDDR5 (4 GB)': 3141,
    ' Intel Iris Plus Graphics 655': 1796,
    ' NVIDIA GeForce MX150 (4 GB)': 2359,
    ' NVIDIA GeForce MX250 (4 GB)': 2559,
    ' NVIDIA GeForce MX110 (2 GB)': 1487,
    ' NVIDIA GeForce MX230 (2 GB)': 1932,
    ' Intel HD Graphics 615': 735,
    ' NVIDIA GeForce MX130 (4 GB)': 1931,
    ' NVIDIA GeForce GTX 1050 Ti (4 GB)': 6342,
    ' NVIDIA GeForce MX130 (2 GB)': 1931,
    ' AMD Radeon 520 (2 GB)': 856,
    ' AMD Radeon 530M (4 GB)': 932,
    ' Intel Graphics 620': 921,
    ' Intel UHD Graphics 600': 333,
    ' AMD Radeon 540 (4 GB)': 1311,
    ' NVIDIA GeForce MX250 (2 GB)': 2559,
    ' NVIDIA GeForce GTX 1050 (3 GB)': 5225,
    ' Intel Iris Plus Graphics 645': 1748,
    ' Intel HD Graphics 400': 332,
    ' Intel Iris Plus Graphics 640': 1309,
    ' Intel HD Graphics 505': 344,
    ' Intel HD Graphics 500': 304,
    ' Radeon Pro 560X GDDR5 (4 GB)': 3678,
    ' NVIDIA GeForce GTX 1080 (8 GB) SLI': 15021,
    ' NVIDIA GeForce GTX 1070 (8 GB)': 13359,
    ' NVIDIA GeForce GTX 980M (8 GB)': 7313,
    ' AMD Radeon R9-M370X (2 GB)': 1376,
    ' NVIDIA GeForce GTX 1080 (8 GB)': 15021,
    ' NVIDIA GeForce GTX 1050 (4 GB)': 6342,
    ' Radeon Pro 555 GDDR5 (2 GB)': 3141,
    ' AMD Radeon 535 (2 GB)': 1116,
    ' Intel Iris Pro Graphics': 1464,
    ' Intel Iris Plus Graphics 650': 1607,
    ' Intel HD Graphics 520': 862,
    ' NVIDIA GeForce GT 940MX (2 GB)': 1543,
    ' AMD Radeon R5-M340 (2 GB)': 549,
    ' AMD Radeon R7-M445 (4 GB)': 902,
    ' NVIDIA GeForce 940MX (4 GB)': 1543,
    ' NVIDIA GeForce 940MX (2 GB)': 1543,
    ' Intel Iris Graphics 550': 1335,
    ' AMD Radeon R5-M430 (2 GB)': 649
}
df2['graphics_card_score'] = df2['graphics_card'].map(d)
df2.head()

,brand,laptop_name,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max,disk_type,graphics_card_score
0,HP,Notebook 14-df0008nx,14.0,Intel Celeron N4000,Intel HD Graphics 600,64.0,1259.0,1259.0,0.0,eMMC,153
1,Lenovo,IdeaPad 330S-14IKB,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1024.0,1849.0,2099.0,3.3,HDD,1050
2,Huawei,MateBook D Volta,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256.0,2999.0,3799.0,0.0,SSD,2359
3,Dell,Inspiron 15 3567,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1024.0,1849.0,1849.0,0.0,HDD,921
4,Asus,VivoBook 15 X510UR,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1024.0,2499.0,3149.0,0.0,HDD,1336

## processor type

In [12]:
df2['processor_type'].unique()

array([' Intel Celeron N4000', ' Intel Core i5-8250U',
       ' Intel Core i3-7020U', ' Intel Core i7-8550U',
       ' Intel Core i5 Dual Core', ' AMD A9-9425', ' Intel Core i7-8565U',
       ' Intel Core i7 6 Core', ' Intel Core i5 Quad Core',
       ' Intel Core i5-8265U', ' Intel Core M3', ' Intel Core i7-8750H',
       ' Intel Core i3-8145U', ' Intel Celeron 4205U',
       ' Intel Celeron N3060', ' Intel Celeron N3350',
       ' Intel Core i5-7200U', ' Intel Core i9', ' Intel Core i7-7820HK',
       ' Intel Core i7-7700HQ', ' Intel Core i7-6700HQ',
       ' Intel Core i7 Quad Core', ' Intel Core i7-7500U',
       ' Intel Core i3-5005U', ' Intel Core i3-6006U',
       ' Intel Core i3-8130U'], dtype=object)

In [13]:
d = {
    ' Intel Celeron N4000': 1436,
    ' Intel Core i5-8250U': 5977,
    ' Intel Core i3-7020U': 2591,
    ' Intel Core i7-8550U': 5955,
    ' Intel Core i5 Dual Core': 6496,
    ' AMD A9-9425': 1546,
    ' Intel Core i7-8565U': 6388,
    ' Intel Core i7 6 Core': 6515,
    ' Intel Core i5 Quad Core': 3819,
    ' Intel Core i5-8265U': 6131,
    ' Intel Core M3': 1502,
    ' Intel Core i7-8750H': 10185,
    ' Intel Core i3-8145U': 3814,
    ' Intel Celeron 4205U': 1311,
    ' Intel Celeron N3060': 674,
    ' Intel Celeron N3350': 1158,
    ' Intel Core i5-7200U': 3398,
    ' Intel Core i9': 18864,
    ' Intel Core i7-7820HK': 7814,
    ' Intel Core i7-7700HQ': 6961,
    ' Intel Core i7-6700HQ': 6515,
    ' Intel Core i7 Quad Core': 10082,
    ' Intel Core i7-7500U': 3666,
    ' Intel Core i3-5005U': 2026,
    ' Intel Core i3-6006U': 2288,
    ' Intel Core i3-8130U': 3677
}

df2['processor_score'] = df2['processor_type'].map(d)
df2.head()

,brand,laptop_name,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max,disk_type,graphics_card_score,processor_score
0,HP,Notebook 14-df0008nx,14.0,Intel Celeron N4000,Intel HD Graphics 600,64.0,1259.0,1259.0,0.0,eMMC,153,1436
1,Lenovo,IdeaPad 330S-14IKB,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1024.0,1849.0,2099.0,3.3,HDD,1050,5977
2,Huawei,MateBook D Volta,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256.0,2999.0,3799.0,0.0,SSD,2359,5977
3,Dell,Inspiron 15 3567,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1024.0,1849.0,1849.0,0.0,HDD,921,2591
4,Asus,VivoBook 15 X510UR,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1024.0,2499.0,3149.0,0.0,HDD,1336,5955

## laptop_name

##### I don't believe laptop_name is going to have an impact so will just drop it

In [14]:
df2.drop(columns=['laptop_name'], inplace=True)
df2.head()

,brand,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max,disk_type,graphics_card_score,processor_score
0,HP,14.0,Intel Celeron N4000,Intel HD Graphics 600,64.0,1259.0,1259.0,0.0,eMMC,153,1436
1,Lenovo,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1024.0,1849.0,2099.0,3.3,HDD,1050,5977
2,Huawei,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256.0,2999.0,3799.0,0.0,SSD,2359,5977
3,Dell,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1024.0,1849.0,1849.0,0.0,HDD,921,2591
4,Asus,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1024.0,2499.0,3149.0,0.0,HDD,1336,5955

## brand

##### Maybe laptops from same brands be more similar. We can treat the brand like a categorical variable and create dummies columns in its place.

In [15]:
df2['brand'].unique()

array(['HP', 'Lenovo', 'Huawei', 'Dell', 'Asus', 'Apple', 'Acer',
       'Microsoft', 'MSI'], dtype=object)

In [16]:
df2.drop(columns=['processor_type', 'graphics_card'], inplace=True)
df2 = pd.get_dummies(df2)
df2.head()

,display_size,disk_space,discount_price,old_price,ratings_5max,graphics_card_score,processor_score,brand_Acer,brand_Apple,brand_Asus,brand_Dell,brand_HP,brand_Huawei,brand_Lenovo,brand_MSI,brand_Microsoft,disk_type_Flash,disk_type_HDD,disk_type_SSD,disk_type_eMMC
0,14.0,64.0,1259.0,1259.0,0.0,153,1436,0,0,0,0,1,0,0,0,0,0,0,0,1
1,14.0,1024.0,1849.0,2099.0,3.3,1050,5977,0,0,0,0,0,0,1,0,0,0,1,0,0
2,14.0,256.0,2999.0,3799.0,0.0,2359,5977,0,0,0,0,0,1,0,0,0,0,0,1,0
3,15.6,1024.0,1849.0,1849.0,0.0,921,2591,0,0,0,1,0,0,0,0,0,0,1,0,0
4,15.6,1024.0,2499.0,3149.0,0.0,1336,5955,0,0,1,0,0,0,0,0,0,0,1,0,0

## Similarity Matrix
##### Create and save our similarity matrix

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

df2_numpy = df2.values
similarity_matrix = cosine_similarity(df2_numpy)
sim_sorted = np.vstack([np.argsort(-row) for row in similarity_matrix])
np.save("similarity_mtrx", sim_sorted, allow_pickle=False)
sim_sorted.shape

/home/mao919/anaconda3/envs/py37-start/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/mao919/anaconda3/envs/py37-start/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/mao919/anaconda3/envs/py37-start/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/mao919/anaconda3/envs/py37-start/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

(205, 205)

In [18]:
def similars(x):
    sim_ids = sim_sorted[x.name, 1:4]
    for i, item in enumerate(sim_ids):
        item = df.loc[item, 'brand'] + ' ' + df.loc[item, 'laptop_name']
        x[str(i+1)+'st similar'] = item
    return x
df_similarities = df.apply(similars, axis=1)
df_similarities.head()

,brand,laptop_name,display_size,processor_type,graphics_card,disk_space,discount_price,old_price,ratings_5max,1st similar,2st similar,3st similar
0,HP,Notebook 14-df0008nx,14.0,Intel Celeron N4000,Intel HD Graphics 600,64 GB (eMMC),1259.0,1259.0,0 / 5,Apple MacBook Air (Retina),Apple MacBook Air (Retina),Apple MacBook Air (Retina)
1,Lenovo,IdeaPad 330S-14IKB,14.0,Intel Core i5-8250U,Intel UHD Graphics 620,1 TB HDD,1849.0,2099.0,3.3 / 5,Lenovo IdeaPad 330S-14IKB,HP 15-da1005nx,Asus X543UB
2,Huawei,MateBook D Volta,14.0,Intel Core i5-8250U,NVIDIA GeForce MX150 (2 GB),256 GB SSD,2999.0,3799.0,0 / 5,HP Pavilion 15-cs0006nx,HP Pavilion 14-ce2003nx,Asus VivoBook S15 S530FN
3,Dell,Inspiron 15 3567,15.6,Intel Core i3-7020U,Intel HD Graphics 620,1 TB HDD,1849.0,1849.0,0 / 5,HP 15-da0007nx,Acer Aspire 3,Dell Inspiron 15 3581
4,Asus,VivoBook 15 X510UR,15.6,Intel Core i7-8550U,NVIDIA GeForce 930MX (2 GB),1 TB HDD,2499.0,3149.0,0 / 5,Asus X543UB,Asus VivoBook 14 X412UB,Acer Aspire 5 A515-52G-75XJ

In [24]:
df[df['laptop_name'] == df.loc[0, 'laptop_name']].index

Int64Index([0], dtype='int64')

In [33]:
df.loc[103]

brand                                Apple
laptop_name           MacBook Air (Retina)
display_size                          13.3
processor_type     Intel Core i5 Dual Core
graphics_card       Intel UHD Graphics 617
disk_space               256 GB (PCIe SSD)
discount_price                        5649
old_price                             5649
ratings_5max                         0 / 5
Name: 103, dtype: object